project:
  type: book
  output-dir: docs
  
book:
  title: "Inferência Estatística - um curso de graduação"
  author: "James D Santos"
  date: "24/08/2024"
  chapters:
    - index.qmd
    - summary.qmd
    - intro.qmd
    - suficiencia.qmd
    - pontual.qmd
    - references.qmd
    - teste.qmd
    - intervalo.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    pdf-engine: pdflatex
    documentclass: scrartcl
    toc: true
    number-sections: true
    colorlinks: true
  epub:
    cover-image: cover.png
